name: Deploy Feedback Service

on:
  push:
    paths:
      - 'feedback-service/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build JAR with Maven
        run: |
          cd feedback-service
          mvn clean package -DskipTests
          cd ..

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/feedback-service:${{ github.sha }} ./feedback-service

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/feedback-service:${{ github.sha }}

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: feedback-service
          images: ${{ secrets.ACR_NAME }}.azurecr.io/feedback-service:${{ github.sha }}
