name: Deploy Reporting Service

on:
  push:
    paths:
      - 'reporting-service/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build JAR with Maven
        run: |
          cd reporting-service
          mvn clean package -DskipTests
          cd ..

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/reporting-service:${{ github.sha }} ./reporting-service

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/reporting-service:${{ github.sha }}

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: reporting-service
          images: ${{ secrets.ACR_NAME }}.azurecr.io/reporting-service:${{ github.sha }}
