name: Deploy Discovery Service

on:
  push:
    paths:
      - 'discovery-service/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build JAR with Maven
        run: |
          cd discovery-service
          mvn clean package -DskipTests
          cd ..

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/discovery-service:${{ github.sha }} ./discovery-service

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_NAME }}.azurecr.io/discovery-service:${{ github.sha }}

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: discovery-service
          images: ${{ secrets.ACR_NAME }}.azurecr.io/discovery-service:${{ github.sha }}
